[custom]
;自定义域名
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/wdsjjszr/sub_mine/refs/heads/main/CustomRules/DIRECT.list
surge_ruleset=🚀 全局设置,https://raw.githubusercontent.com/wdsjjszr/sub_mine/refs/heads/main/CustomRules/GLOBAL.list
surge_ruleset=🛑 广告拦截,https://raw.githubusercontent.com/wdsjjszr/sub_mine/refs/heads/main/CustomRules/REJECT.list

surge_ruleset=🐶 Adobe,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Adobe.list
surge_ruleset=💚 iwara,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Iwara.list
surge_ruleset=🐼 exhentai,https://raw.githubusercontent.com/wdsjjszr/sub_mine/refs/heads/main/CustomRules/exhentai.list
surge_ruleset=👨‍💻 github,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Github.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Download.list ;下载
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/GameDownload.list ;下载2
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
surge_ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
surge_ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
surge_ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
surge_ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
surge_ruleset=Ⓜ️ 微软服务,https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Microsoft.list
surge_ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
surge_ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
surge_ruleset=🤖 ChatGPT,https://raw.githubusercontent.com/lhl77/sub-ini/main/openai.list
;surge_ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
surge_ruleset=🎮 国际游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
surge_ruleset=🎮 国际游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
surge_ruleset=🎮 国际游戏,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
surge_ruleset=📹 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;surge_ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
;surge_ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
surge_ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
surge_ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
surge_ruleset=🌏 出海媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
surge_ruleset=🌏 出海媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/IqiyiHMT.list
surge_ruleset=🚀 全局设置,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
surge_ruleset=🎯 国内网络,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
surge_ruleset=🎯 国内网络,[]GEOIP,CN
;surge_ruleset=🐼 つつ,https://raw.githubusercontent.com/lhl77/sub-ini/master/tsutsuDomain.list
surge_ruleset=🐟 其他网站,[]FINAL



custom_proxy_group=🚀 全局设置`select`[]🚀 手动选择`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]DIRECT
custom_proxy_group=🚀 手动选择`select`.*
custom_proxy_group=🐟 其他网站`select`[]DIRECT`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动选择
custom_proxy_group=♻️ 低倍率自动选择`url-test`(日用|0\.2)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(Traffic|Expire|重置)).*)`http://www.gstatic.com/generate_204`60,,10 ;每60秒探测一次, 失败即切换,超时时间10秒
custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(Traffic|Expire|重置)).*)`http://www.gstatic.com/generate_204`60,,10
custom_proxy_group=🎯 国内网络`select`[]DIRECT`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🚀 手动选择`[]🔑 专用线路
custom_proxy_group=👨‍💻 github`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=🤖 ChatGPT`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=📹 Youtube`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=💚 iwara`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=🐼 exhentai`select`[]🚀 全局设置`(^(?!.*(Traffic|Expire)).*)
custom_proxy_group=🐶 Adobe`select`[]REJECT`[]DIRECT`[]🚀 全局设置
;custom_proxy_group=🎥 Netflix`select`[]🎥 奈飞节点`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
;custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 全局设置`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
;custom_proxy_group=🐼 つつ`select`[]🚀 全局设置`[]DIRECT`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择
custom_proxy_group=🌍 国外媒体`select`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🔑 专用线路`[]🚀 手动选择
custom_proxy_group=🌏 出海媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🔑 专用线路`[]🚀 手动选择
custom_proxy_group=📢 谷歌FCM`select`[]🚀 全局设置`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🚀 全局设置`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 全局设置`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 全局设置`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择
custom_proxy_group=🎮 国际游戏`select`[]🚀 全局设置`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🔑 专用线路`[]🚀 手动选择`[]DIRECT
;custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 全局设置`[]♻️ 低倍率自动选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇸🇬 新加坡节点`select`(新|新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韩)
;custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|原生)
custom_proxy_group=🔑 专用线路`select`(IPLC|IEPL|iplc|iepl|专线|游戏)
enable_rule_generator=true
overwrite_original_rules=true
